name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.7
  - numpy
  - conda-build
  - pyyaml
  - ipython
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - pip
    - fastai
    - fastcore
    - fastprogress==1.0.0
